name = "stremio-http-bridge"
main = "src/index.js"
compatibility_date = "2025-11-17"

# Aquí definimos las variables. 
# Recomiendo configurarlas en el Dashboard de Cloudflare o usando 'wrangler secret put',
# pero para pruebas rápidas puedes descomentar la línea de abajo y poner tu URL.

[vars]
STREMIO_SERVER_URL = "https://stremioproxied.sakvragi.workers.dev" 
# DEJA ESTO COMENTADO SI USAS SECRETOS (RECOMENDADO)
